export const CHANGE_HUE = "CHANGE_HUE";
export const CHANGE_LIGHT = "CHANGE_LIGHT";
export const CHANGE_SATURATION = "CHANGE_SATURATION";
export const SELECT_PALLET = "SELECT_PALLET";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const SET_USERS = "SET_USERS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
